import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import logo from '../src/atempologo.png'
import btn from '../src/lateral.png'
import MainHead from '../components/MainHead'

export default function Home() {
  return (
    <>
      <MainHead titulo="Atempøral"/>

      <div className={styles.container}>

      <div className={styles.header}>
      <Image src={logo} width={250} height={48} />
      <button className={styles.btnLateral}>
        <span class="material-symbols-outlined">menu</span>
      </button>
      <div className={styles.botonera}>
      <button className={styles.btnMenu}>
        <font face="Work Sans" size='3'>
          <h3>Botón</h3>
        </font>
      </button>
      <button className={styles.btnMenu}>
        <font face="Work Sans" size='3'>
          <h3>Botón</h3>
        </font>
      </button>
      <button className={styles.btnMenu}>
        <font face="Work Sans" size='3'>
          <h3>Botón</h3>
        </font>
      </button>
      <button className={styles.btnMenu}>
        <font face="Work Sans" size='3'>
          <h3>Botón</h3>
        </font>
      </button>
      <button className={styles.btnMenu}>
        <font face="Work Sans" size='3'>
          <h3>Botón</h3>
        </font>
      </button>
      <button className={styles.btnMenu}>
        <font face="Work Sans" size='3'>
          <h3>Botón</h3>
        </font>
      </button>
      <button className={styles.btnMenu}>
        <font face="Work Sans" size='3'>
          <h3>Botón</h3>
        </font>
      </button>
      </div>
      </div>
      
      <div className={styles.page}>
      <font face="Work Sans">
      <center><h1>contenido</h1></center>
        </font>
      </div>
      
      </div>

    </>
  )
}

/*
<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>





*/